<div class="mainBlock">
    <div class="video__welcome" data-current="0">
        <video autoplay="" muted="" loop="" src="/media/rotang-mebel.mp4">
            <source src="/media/rotang.mov">
        </video>
        <div class="home__background--mobile"></div>
        <div class="container my-auto">
            <h2 class="video__header header__text">Стиль & Комфорт</h2>
            <p class="header__text"><span class="text_cont_inner">Добавьте ощущение уюта в ваше жизненное пространство</span></p>
            <a href="<?=$this->helper('krasnov_catalog')->getCatalogUrl() ?>">Перейти в каталог</a>
        </div>
    </div>
    <div class="whywe">
        <p class="why caption">Почему мы?</p>
        <div class="whyWeFlexContainer">
            <div class="whyWeBlocks col-sm-11 col-xs-11 col-md-5 col-lg-5">
                <div class="row">
                    <div class="whyWeLeft"><img src="/media/deal.png" /></div>
                    <div class="whyWeRight">У нас выгодные цены</div>
                </div>
            </div>
            <div class="whyWeBlocks col-sm-11 col-xs-11 col-md-5 col-lg-5">
                <div class="row">
                    <div class="whyWeLeft"><img src="/media/customer.png" /></div>
                    <div class="whyWeRight">Индивидуальный подход</div>
                </div>
            </div>
            <div class="whyWeBlocks col-sm-11 col-xs-11 col-md-5 col-lg-5">
                <div class="row">
                    <div class="whyWeLeft"><img src="/media/recommended.png" /></div>
                    <div class="whyWeRight">Высокое качество</div>
                </div>
            </div>
            <div class="whyWeBlocks col-sm-11 col-xs-11 col-md-5 col-lg-5">
                <div class="row">
                    <div class="whyWeLeft"><img src="/media/heart.png" /></div>
                    <div class="whyWeRight">Мы любим нашу работу</div>
                </div>
            </div>
        </div>
    </div>
    <div class="pitAbout pitAboutFirst">
        <div class="row">
            <div class="col-md-7 pitAboutLeft"></div>
            <div class="col-md-9 col-sm-12 pitAboutRight">
                <div class="row">
                    <div class="col-md-8 pitAboutCenter" id="about-us-main">
                        <div class="pitAboutTitle">О компании</div>
                        <div class="pitAboutInfo">Фабрика мебели из экоротанга "ПлатовЪ", расположена в Ростовской области, у берега Азовского моря, на территории бывшего имения героя Отечественной войны, Атамана Войска Донского - Матвея Ивановича Платова.
                            Всё изделия изготавливаются вручную, профессионалами своего дела. Каждое изделие проходит 4-х ступенчатую систему контроля качества. В наличии и под заказ всевозможные варианты мебели на любой вкус и бюджет. Огромная палитра цветов как экоротанга, так и текстиля, создаёт условия для создания идеального и гармоничного интерьера. </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="pitAbout">
        <div class="row">
            <div class="col-md-7 pitAboutRightForSecond"></div>
            <div class="col-md-9 col-sm-12 pitAboutLeftForSecond">
                <div class="row">
                    <div class="col-md-8 pitAboutCenter pitAboutCenterSecond">
                        <div class="pitAboutTitle">В чем наши преимущества</div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xm-12 pitFeatureCont pitLeftFeatCont">
                            <div class="row">
                                <div class="col-sm-12">Мы являемся производителями и поэтому можем гарантировать широкий ассортиментный ряд при действительно доступных ценах.</div>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xm-12 pitFeatureCont pitRightFeatCont">
                            <div class="row">
                                <div class="col-sm-12">Наших постоянных клиентов ждут скидки и особые, индивидуальные условия сотрудничества.</div>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xm-12 pitFeatureCont pitLeftFeatCont">
                            <div class="row">
                                <div class="col-sm-12">Специалисты нашей компании всегда предоставят квалифицированную консультацию по выбору мебели.</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="contact">
        <div class="margin_block">
            <div class="container home__blocks-container">
                <div class="row">
                    <div class="col-md-3 col-sm-6">
                        <div class="info_box inLeft" style="opacity: 1; animation-fill-mode: none;">
                            <div class="icon icolor_v1"><i aria-hidden="true" class="fa fa-address-card"></i></div>
                            <h2>О нас</h2>
                            <p>Здесь Вы можете узнать интересные сведения о нашей компании.</p>
                            <a href="#about-us-main" class="linkToId"> <button class="submit">Перейти</button> </a></div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="info_box inUp" style="opacity: 1; animation-fill-mode: none;">
                            <div class="icon icolor_v1"><i aria-hidden="true" class="fa fa-percent"></i></div>
                            <h2>Акции</h2>
                            <p>Здесь Вы можете ознакомиться с актуальными акциями на нашу продукцию. </p>
                            <a href="/shares"> <button class="submit">Перейти</button> </a></div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="info_box inDown" style="opacity: 1; animation-fill-mode: none;">
                            <div class="icon icolor_v1"><i aria-hidden="true" class="fa fa-shopping-cart"></i></div>
                            <h2>Каталог</h2>
                            <p>Здесь Вы можете просмотреть полный список наших товаров.</p>
                            <a href="<?=$this->helper('krasnov_catalog')->getCatalogUrl() ?>"> <button class="submit">Перейти</button> </a></div>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <div class="info_box inDown" style="opacity: 1; animation-fill-mode: none;">
                            <div class="icon icolor_v1"><i aria-hidden="true" class="fa fa-address-card"></i></div>
                            <h2>Контакты</h2>
                            <p>Вы можете связаться с нами любым удобным для Вас способом.</p>
                            <a href="#footer-contacts" class="linkToId"> <button class="submit">Перейти</button> </a></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {{block type="gallery/slider" template="gallery/slider.phtml"}}
    <div class="map"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2713.5826034055544!2d38.343142715860196!3d47.146442927644394!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40e6b106ccbf66eb%3A0xa0bc2535486269e0!2z0KHQvtCy0LXRgtGB0LrQsNGPINGD0LsuLCAzOSwg0JLQtdGB0LXQu9C-LdCS0L7Qt9C90LXRgdC10L3QutCwLCDQoNC-0YHRgtC-0LLRgdC60LDRjyDQvtCx0LsuLCAzNDY4NjE!5e0!3m2!1sru!2sru!4v1590319614581!5m2!1sru!2sru" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe></div>
</div>